name: CI
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - run: npm ci
      - name: Test
        run: npm run test
        env:
          HELLO: ${{ secrets.HELLO }}

  automerge:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: dancamma/github-action-merge-dependabot@498-fail-with-error-unsupported-trigger
        with:
          target: major
          skip-trigger-verification: true
