name: CI
on:
  pull_request_target:
    types:
      - opened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - run: npm ci
      - name: Test
        run: npm run test
        env:
          HELLO: ${{ secrets.HELLO }}

  automerge:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: diranged/github-action-merge-dependabot@672c9104e034cd03274dd625a955cf60d21ed011
        with:
          target: major
          event-name: pull_request_target
